general.live_config_reload = true
general.import = [
	"~/.config/alacritty/extra_configs/linux_keybinds.toml",
]

[env]
	alacritty_dir="~/.config/alacritty/"

[scrolling]
	history = 10000
	multiplier = 5


[window]
	padding = { x = 15, y = 10 }
	decorations = "None"
	opacity = 0.85
	startup_mode = "Maximized"
	title = "Terminal"
	dynamic_title = true
	decorations_theme_variant = "Dark"
	level = "Normal" #can be <AlwaysOnTop>

[font]
	# normal = { family = "Nimbus Mono", style = "Regular" }
	normal = { family = "DejaVu Sans Mono", style = "Regular" }

#[terminal]
#shell = { program = "/bin/bash", args = ["-c", "tmux attach || tmux"] }

[cursor]
	style = { shape = "Block", blinking = "Always" }
	blink_interval = 500

[colors]
	draw_bold_text_with_bright_colors = true

	cursor = { text = "CellBackground", cursor = "CellForeground" }
	vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

	[colors.search]
		matches = { foreground = "#202020", background = "#ac4242" }
		focused_match = { foreground = "#181818", background = "#f4bf75" }

	[colors.primary]
		background = '#05021e'
		foreground = '#d8d8d8'
		dim_foreground = '#848484'
		bright_foreground = '#d899d8'

	[colors.normal]
		black =		'#002221'
		red =		'#ea3431'
		green =		'#00b6b6'
		yellow =	'#f8b017'
		blue =		'#4894fd'
		magenta =	'#e01dca'
		cyan =		'#1ab2ad'
		white = 	'#99dddb'
	
	[colors.bright]
		black =		'#006562'
		red =		'#ea3431'
		green =		'#00b6b6'
		yellow =	'#f8b017'
		blue =		'#4894fd'
		magenta =	'#e01dca'
		cyan =		'#1ab2ad'
		white =		'#e6f6f6'

[mouse]
	hide_when_typing = true




